------------------------------------------------------------
---CLEAN DATASET (UTC to SA time, duration to seconds)
CREATE OR REPLACE TABLE brighttv1.data2.tvdata_clean AS
SELECT 
USERID,
CHANNEL2,

---Raw UTC timestamp
TO_TIMESTAMP(RECORDDATE2, 'YYYY/MM/DD HH24:MI') AS RECORD_TS_UTC,

---SA time
CONVERT_TIMEZONE(
'UTC', 'Africa/Johannesburg',
TO_TIMESTAMP(RECORDDATE2, 'YYYY/MM/DD HH24:MI')
) AS RECORD_TS_SA,

---Day name (Mon–Sun)
INITCAP(TO_CHAR(
CONVERT_TIMEZONE(
'UTC', 'Africa/Johannesburg',
TO_TIMESTAMP(RECORDDATE2, 'YYYY/MM/DD HH24:MI')
), 'DY' )) AS DAY_NAME,

---Duration to seconds
(SPLIT_PART(DURATION2, ':', 1)::INT * 3600 +SPLIT_PART(DURATION2, ':', 2)::INT * 60 +
SPLIT_PART(DURATION2, ':', 3)::INT
) AS DURATION_SECONDS

FROM brighttv1.data2.tvdata;
-------------------------------------------------------------
SELECT
USERID,
CHANNEL2,
RECORD_TS_SA,
DATE(RECORD_TS_SA) AS WATCH_DATE,
TO_CHAR(RECORD_TS_SA, 'MON') AS WATCH_MONTH,
EXTRACT(MONTH FROM RECORD_TS_SA) AS MONTH_NUM,
INITCAP(TO_CHAR(RECORD_TS_SA, 'DY')) AS DAY_NAME,
EXTRACT(HOUR FROM RECORD_TS_SA) AS WATCH_HOUR,
DURATION_SECONDS,
DURATION_SECONDS / 3600 AS HOURS_WATCHED
FROM brighttv1.data2.tvdata_clean;
